// Canonical dev/test seed data — single source of truth. Both the in-memory
// test seed (cire/api/src/db/setup.ts#seedDb) and the local-D1 SQL seed
// (cire/db/seed/dev-seed.sql, regenerated by ./generate.ts) derive from here.
export { events } from "./events";
export type { DressCodeSwatch, SeedEvent } from "./events";
export { guests } from "./guests";
export type { SeedFamily, SeedGuest } from "./guests";
export { bootstrapWedding, DEV_OWNER_PROFILE_ID } from "./wedding";
