#!/usr/bin/env bun
/**
 * Emits the Swift set of osn-api operations that require a bearer token,
 * read straight from `shared/openapi/osn.json`.
 *
 * The Swift OpenAPI generator ignores `security` — it generates types and a
 * client, and leaves auth to a middleware. So the split between "needs a
 * token" and "a signed-out app may call this" has to reach Swift some other
 * way, and a hand-kept list would drift the moment a route gains or loses
 * its auth gate. This derives it; `OSNAPITests` fails if the checked-in file
 * and the spec disagree.
 *
 *   bun run scripts/generate-osn-authenticated-operations.ts
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const specPath = join(repoRoot, "shared/openapi/osn.json");
const outputPath = join(
  repoRoot,
  "shared/swift/OSNShared/Sources/OSNAPI/OSNAuthenticatedOperations.swift",
);

const HTTP_METHODS = new Set(["get", "put", "post", "delete", "patch", "options", "head", "trace"]);

type Operation = { operationId?: string; security?: unknown[] };

export function authenticatedOperationIDs(spec: {
  paths: Record<string, Record<string, Operation>>;
}): string[] {
  const ids: string[] = [];
  for (const pathItem of Object.values(spec.paths)) {
    for (const [method, operation] of Object.entries(pathItem)) {
      if (!HTTP_METHODS.has(method)) continue;
      // An empty `security: []` is the spec's way of saying "explicitly
      // public", so length matters, not presence.
      if (!operation.security?.length) continue;
      if (!operation.operationId) {
        throw new Error(`${method.toUpperCase()} operation has no operationId — cannot key on it`);
      }
      ids.push(operation.operationId);
    }
  }
  return ids.toSorted();
}

const ids = authenticatedOperationIDs(JSON.parse(readFileSync(specPath, "utf8")));

const swift = `// Generated by scripts/generate-osn-authenticated-operations.ts — do not edit.
// Regenerate after any change to shared/openapi/osn.json:
//
//     bun run scripts/generate-osn-authenticated-operations.ts
//
// OSNAPITests asserts this file still matches the spec, so a route that
// gains or loses its auth gate fails the Swift tests rather than silently
// sending an unauthenticated request.

/// The osn-api operations that carry \`security: [{ bearerAuth: [] }]\`.
/// Everything else — registration, passkey login, \`/token\`, the JWKS
/// document, the OIDC endpoints — must go out with no \`Authorization\`
/// header, since a signed-out app has no token to send.
public enum OSNAuthenticatedOperations {
    public static let operationIDs: Set<String> = [
${ids.map((id) => `        "${id}",`).join("\n")}
    ]

    /// Suitable as \`BearerTokenMiddleware\`'s \`requiresAuthentication\`.
    public static func requiresAuthentication(_ operationID: String) -> Bool {
        operationIDs.contains(operationID)
    }
}
`;

writeFileSync(outputPath, swift);
console.info(`Wrote ${ids.length} authenticated operation IDs to ${outputPath}`);
