import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Merge class strings with Tailwind conflict resolution. Use this when
 * composing arbitrary runtime class sets where conflicts are possible
 * and unpredictable (e.g. two signals that may or may not produce
 * overlapping utilities).
 *
 * For component defaults vs consumer overrides, prefer the `base:`
 * variant pattern instead — write `base:` prefixes directly in source
 * class strings. It resolves conflicts via CSS cascade at zero runtime
 * cost, and Tailwind v4's JIT scanner can see it (it cannot see classes
 * generated by a runtime function).
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export { clsx };
export type { ClassValue };
