import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

/**
 * Merge class strings with Tailwind conflict resolution. Use this when
 * composing arbitrary runtime class sets where conflicts are possible
 * and unpredictable (e.g. two signals that may or may not produce
 * overlapping utilities).
 *
 * For component defaults vs consumer overrides, prefer the `base:`
 * variant pattern with `bx()` instead — it resolves conflicts via CSS
 * cascade at zero runtime cost.
 */
export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

/**
 * @deprecated Write `base:` prefixes directly in class strings instead.
 *
 * Tailwind v4's JIT scanner does static analysis — it cannot see classes
 * generated by a runtime function. Writing `base:` prefixes directly in
 * source ensures the scanner generates the corresponding CSS rules.
 *
 * Before: `bx("bg-card rounded-xl")` — scanner sees "bg-card", never generates base:bg-card CSS
 * After:  `"base:bg-card base:rounded-xl"` — scanner sees base:bg-card, generates correct CSS
 *
 * This function is kept temporarily as an identity function for any
 * remaining call sites. All `@osn/ui` components have been migrated.
 */
export function bx(classes: string): string {
  return classes;
}

export { clsx };
export type { ClassValue };
