// Generated by scripts/generate-osn-authenticated-operations.ts — do not edit.
// Regenerate after any change to shared/openapi/osn.json:
//
//     bun run scripts/generate-osn-authenticated-operations.ts
//
// OSNAPITests asserts this file still matches the spec, so a route that
// gains or loses its auth gate fails the Swift tests rather than silently
// sending an unauthenticated request.

/// The osn-api operations that carry `security: [{ bearerAuth: [] }]`.
/// Everything else — registration, passkey login, `/token`, the JWKS
/// document, the OIDC endpoints — must go out with no `Authorization`
/// header, since a signed-out app has no token to send.
public enum OSNAuthenticatedOperations {
    public static let operationIDs: Set<String> = [
        "acknowledgeAllSecurityEvents",
        "acknowledgeSecurityEvent",
        "addOrganisationMember",
        "approveCrossDeviceLogin",
        "beginEmailChange",
        "beginPasskeyRegistration",
        "beginStepUpOtp",
        "beginStepUpPasskey",
        "blockProfile",
        "completeEmailChange",
        "completePasskeyRegistration",
        "completeStepUpOtp",
        "completeStepUpPasskey",
        "createOrganisation",
        "createProfile",
        "deleteOrganisation",
        "deletePasskey",
        "deleteProfile",
        "disableOidcClient",
        "exportAccount",
        "generateRecoveryCodes",
        "getAccountDeletionStatus",
        "getConnectionStatus",
        "getOrganisation",
        "getRecoveryStatus",
        "isProfileBlocked",
        "listAccountProfiles",
        "listBlocks",
        "listConnections",
        "listMyOrganisations",
        "listOidcClients",
        "listOidcConnections",
        "listOrganisationMembers",
        "listPasskeys",
        "listPendingConnectionRequests",
        "listSecurityEvents",
        "listSentConnectionRequests",
        "listSessions",
        "registerOidcClient",
        "rejectCrossDeviceLogin",
        "removeConnection",
        "removeOrganisationMember",
        "renamePasskey",
        "requestAccountDeletion",
        "respondToConnectionRequest",
        "restoreAccount",
        "revokeAllOtherSessions",
        "revokeOidcConnection",
        "revokeSession",
        "searchProfilesAndOrganisations",
        "sendConnectionRequest",
        "setDefaultProfile",
        "suggestConnections",
        "switchProfile",
        "unblockProfile",
        "updateOrganisation",
        "updateOrganisationMemberRole",
    ]

    /// Suitable as `BearerTokenMiddleware`'s `requiresAuthentication`.
    public static func requiresAuthentication(_ operationID: String) -> Bool {
        operationIDs.contains(operationID)
    }
}
