/**
 * Bounded metric attribute unions for `@shared/redis`.
 *
 * `RedisNamespace` is the closed set of logical key-spaces that live in Redis.
 * It is the single source of truth for the `namespace` attribute on the
 * `redis.store.keys` gauge (and any other per-namespace metric a downstream
 * service emits). Keeping it a closed union enforces the observability rule
 * "no unbounded metric attributes" — a new Redis-backed store MUST add its
 * namespace here before it can be dimensioned, which keeps cardinality
 * reviewable in one place.
 *
 * The string values mirror the key prefixes used by the stores themselves
 * (e.g. `rl:` rate-limit keys, `osn:rot-session:` rotated-session keys). They
 * are intentionally short and stable — renaming one is a metric-continuity
 * break, not just a refactor.
 */
export type RedisNamespace =
  // Phase 1–4 (pre-existing): rate limiting + cluster-safe auth state.
  | "rate_limit"
  | "rotated_session"
  | "step_up_jti"
  // Ceremony / pending-state stores migrated off process-local Maps.
  | "reg_challenge"
  | "login_challenge"
  | "pending_registration"
  | "step_up_challenge"
  | "step_up_otp"
  | "pending_email_change"
  | "cross_device"
  // The TOTP secret generated by /totp/enroll/begin and not yet confirmed. It
  // never reaches D1: an unconfirmed secret is not a credential, and a 10-minute
  // ceremony window is not a reason to write one to the durable store.
  | "pending_totp_enroll"
  // The 6-digit code emailed by /login/recovery/email/begin, awaiting
  // /login/recovery/email/complete. Keyed by accountId, TTL 10 minutes, and it
  // never reaches D1 — a pending recovery code is not a credential.
  | "pending_recovery_otp"
  // Per-account recovery-code lockout counter.
  | "recovery_lockout"
  // Per-account lockout for the email-OTP recovery path. Its own key space so a
  // wrong 6-digit recovery code and a wrong 64-bit recovery code never share a
  // counter — one attacker grinding either must not deny the owner the other.
  | "recovery_otp_lockout"
  // Per-account TOTP failed-attempt lockout. Separate from recovery_lockout
  // because the two have opposite outage postures — see
  // `osn/api/src/lib/recovery-lockout-store.ts`.
  | "totp_lockout"
  // OIDC: validated /authorize requests parked while the consent UI runs.
  | "oidc_authorize_request";
